version: '3.7'
services:
 db_test_blog:
   image: postgres
   environment:
        POSTGRES_HOST_AUTH_METHOD: trust
 web_test_blog:
   build: .
   command: python manage.py runserver 0.0.0.0:8000
   volumes:
     - .:/code
   ports:
     - "8000:8000"
   depends_on:
     - db_test_blog
